ALTER TABLE contracts ADD COLUMN company_sign BOOLEAN DEFAULT FALSE;
ALTER TABLE contracts ADD COLUMN method VARCHAR(255);
ALTER TABLE signatures ADD COLUMN status INT(11) DEFAULT NULL;
ALTER TABLE signatures ADD COLUMN sign_file_path VARCHAR(255) DEFAULT NULL;
