server:
  address: ":4000"

database:
  driver: "mysql"
  url: "root:@tcp(db:3306)/ozge_contract?parseTime=true"

mobizon:
  api_key: "kzf5354b5a1cdd0fe9b2be49831e548923b9cd897c128811f47ef57dd61cbebfba2dd3"

whatsapp:
  token: "EAAKx4I2ZArxMBPW6DoO0P6vnZCW9GV2ZB4r1ZCmiJbxuLBWwI1ZAqIeKNQtVen9xcGIJxo8gkmXhGUhqHBg4A7vZCjHtXyHc8Tty4SjRpMXyoiG4tyz3LIEjCZCU21QmrZC4L98dXl4juV9fNOBRys7tuWCXP3Jgoc1j5gSrrd9ylCHmLKPsfSwTAiyrLnGm5KIrgPsaJ7bIkODYUNLs2j0E0Y3s7xnUnvGhbcffznEmBsw4qVyy"
  phone_number_id: "686358144568271"
